### ISSUE TITLE
Move private key storage (for login) to creds service

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-web-api#702] opened 2024-02-05 18:35 UTC

**Comment by mjtravers** [comment] 2024-02-19 19:57
Duplicate of https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-web-api/110

Closing ticket.

**Closed by mjtravers** 2024-02-19 19:57 UTC
